# =============================================================================
# Happy Tooth Dental Clinic and Services
# Billing View — Billing and payment management
# =============================================================================

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton,
    QLineEdit, QTableWidget, QTableWidgetItem, QHeaderView,
    QDialog, QFormLayout, QComboBox, QDoubleSpinBox,
    QMessageBox, QTextEdit, QTextBrowser, QMenu
)
from PyQt6.QtCore import Qt, QMarginsF, QSize
from PyQt6.QtGui import QPageLayout, QPageSize, QAction
from PyQt6.QtPrintSupport import QPrinter, QPrintDialog
import qtawesome as qta
from datetime import datetime


class BillingView(QWidget):
    """Billing management page."""
    
    def __init__(self):
        super().__init__()
        self.init_ui()
    
    def init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(28, 24, 28, 24)
        layout.setSpacing(20)
        
        header_layout = QHBoxLayout()
        
        title_icon = QLabel()
        title_icon.setPixmap(qta.icon('fa5s.file-invoice-dollar', color='#1A6E7A').pixmap(24, 24))
        title_icon.setStyleSheet("background: transparent;")
        header_layout.addWidget(title_icon)
        
        title = QLabel("Billing & Payments")
        title.setObjectName("section_title")
        header_layout.addWidget(title)
        header_layout.addStretch()
        
        self.search_input = QLineEdit()
        self.search_input.setObjectName("search_input")
        self.search_input.setPlaceholderText("Search billings...")
        self.search_input.setMaximumWidth(320)
        self.search_input.setMinimumHeight(44)
        header_layout.addWidget(self.search_input)
        
        self.add_btn = QPushButton("  Generate Bill")
        self.add_btn.setObjectName("primary_btn")
        self.add_btn.setIcon(qta.icon('fa5s.plus', color='white'))
        self.add_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        header_layout.addWidget(self.add_btn)
        
        layout.addLayout(header_layout)
        
        self.table = QTableWidget()
        self.table.setColumnCount(9)
        self.table.setHorizontalHeaderLabels([
            "Date", "Patient", "Dentist",
            "Total (₱)", "Paid (₱)", "Balance (₱)", "Status", "Generated By", "Actions"
        ])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.Fixed)
        self.table.setColumnWidth(8, 80)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.verticalHeader().setVisible(False)
        layout.addWidget(self.table)
    
    def load_table(self, billings):
        self.table.setRowCount(0)
        for row_num, bill in enumerate(billings):
            self.table.insertRow(row_num)
            
            date_item = QTableWidgetItem(str(bill.get('appointment_date', '')))
            date_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row_num, 0, date_item)
            
            patient_item = QTableWidgetItem(bill.get('patient_name', ''))
            patient_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row_num, 1, patient_item)
            
            dentist_item = QTableWidgetItem(bill.get('dentist_name', ''))
            dentist_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row_num, 2, dentist_item)
            
            total_item = QTableWidgetItem(f"₱{float(bill['total_amount']):,.2f}")
            total_item.setTextAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
            self.table.setItem(row_num, 3, total_item)
            
            paid_item = QTableWidgetItem(f"₱{float(bill['amount_paid']):,.2f}")
            paid_item.setTextAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
            self.table.setItem(row_num, 4, paid_item)
            
            balance_val = float(bill['balance'])
            if balance_val < 0:
                balance_item = QTableWidgetItem(f"Change: ₱{abs(balance_val):,.2f}")
                balance_item.setForeground(Qt.GlobalColor.darkGreen)
            else:
                balance_item = QTableWidgetItem(f"₱{balance_val:,.2f}")
            balance_item.setTextAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
            self.table.setItem(row_num, 5, balance_item)
            
            status = bill.get('payment_status', 'Unpaid')
            status_item = QTableWidgetItem(status)
            status_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            if status == 'Paid':
                status_item.setForeground(Qt.GlobalColor.darkGreen)
            elif status == 'Partial':
                status_item.setForeground(Qt.GlobalColor.darkYellow)
            else:
                status_item.setForeground(Qt.GlobalColor.red)
            self.table.setItem(row_num, 6, status_item)
            
            # Generated By
            generated_by_name = bill.get('generated_by_name', '') or 'N/A'
            generated_item = QTableWidgetItem(generated_by_name)
            generated_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row_num, 7, generated_item)
            
            # Action dropdown button
            action_widget = QWidget()
            action_layout = QHBoxLayout(action_widget)
            action_layout.setContentsMargins(0, 0, 0, 0)
            action_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
            
            action_btn = QPushButton()
            action_btn.setIcon(qta.icon('fa5s.ellipsis-h', color='#1A6E7A'))
            action_btn.setIconSize(QSize(16, 16))
            action_btn.setCursor(Qt.CursorShape.PointingHandCursor)
            action_btn.setFixedSize(36, 32)
            action_btn.setStyleSheet("""
                QPushButton { background: #FFFFFF; border: 1px solid #D4E6E9; border-radius: 6px; padding: 0px; text-align: center; }
                QPushButton:hover { background: #E8F4F5; border-color: #1A6E7A; }
                QPushButton::menu-indicator { image: none; width: 0px; }
            """)
            
            menu = QMenu(action_btn)
            menu.setStyleSheet("""
                QMenu { background: white; border: 1px solid #D4E6E9; border-radius: 8px; padding: 4px; }
                QMenu::item { padding: 8px 20px; border-radius: 4px; }
                QMenu::item:selected { background: #E8F4F5; color: #1A6E7A; }
            """)
            
            pay_action = QAction("Process Payment", menu)
            pay_action.triggered.connect(lambda _, bid=bill['id']: self._edit_callback(bid) if hasattr(self, '_edit_callback') else None)
            menu.addAction(pay_action)
            
            receipt_action = QAction("View Receipt", menu)
            receipt_action.triggered.connect(lambda _, bid=bill['id']: self._receipt_callback(bid) if hasattr(self, '_receipt_callback') else None)
            menu.addAction(receipt_action)
            
            delete_action = QAction("Delete", menu)
            delete_action.triggered.connect(lambda _, bid=bill['id']: self._delete_callback(bid) if hasattr(self, '_delete_callback') else None)
            menu.addAction(delete_action)
            
            action_btn.setMenu(menu)
            action_layout.addWidget(action_btn)
            
            self.table.setCellWidget(row_num, 8, action_widget)
            self.table.setRowHeight(row_num, 60)

    # ---- Message helpers (keep PyQt6 UI logic in the view) ----
    def show_info(self, title, message):
        QMessageBox.information(self, title, message)

    def show_warning(self, title, message):
        QMessageBox.warning(self, title, message)

    def show_confirm(self, title, message):
        reply = QMessageBox.question(
            self, title, message,
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No
        )
        return reply == QMessageBox.StandardButton.Yes


class BillingDialog(QDialog):
    """Dialog for generating a bill from an appointment."""
    
    def __init__(self, parent=None, billing_data=None, appointments=None, treatment_totals=None):
        super().__init__(parent)
        self.billing_data = billing_data
        self._appointments = appointments or []
        self._treatment_totals = treatment_totals or {}
        self.setWindowTitle("Process Payment" if billing_data else "Generate Bill")
        self.setMinimumWidth(480)
        self.setStyleSheet("QDialog { background-color: #FFFFFF; }")
        self.init_ui()
    
    def init_ui(self):
        layout = QVBoxLayout(self)
        layout.setSpacing(12)
        layout.setContentsMargins(30, 25, 30, 25)
        
        title = QLabel("Process Payment" if self.billing_data else "Generate Bill")
        title.setObjectName("section_title")
        layout.addWidget(title)
        
        form = QFormLayout()
        form.setSpacing(10)
        
        if not self.billing_data:
            # Generate bill — select appointment
            self.appointment_combo = QComboBox()
            self.appointment_combo.setMinimumHeight(38)
            for a in self._appointments:
                label = f"{a['patient_name']} — {a['appointment_date']} ({a['status']})"
                self.appointment_combo.addItem(label, a['id'])
            self.appointment_combo.currentIndexChanged.connect(self._update_total)
            form.addRow(self._label("Appointment *"), self.appointment_combo)
        
        self.total_input = QDoubleSpinBox()
        self.total_input.setPrefix("₱ ")
        self.total_input.setMaximum(999999.99)
        self.total_input.setDecimals(2)
        self.total_input.setMinimumHeight(38)
        form.addRow(self._label("Total Amount"), self.total_input)
        
        self.paid_input = QDoubleSpinBox()
        self.paid_input.setPrefix("₱ ")
        self.paid_input.setMaximum(999999.99)
        self.paid_input.setDecimals(2)
        self.paid_input.setMinimumHeight(38)
        form.addRow(self._label("Amount Paid"), self.paid_input)
        
        self.method_combo = QComboBox()
        self.method_combo.addItems(["Cash", "GCash", "Card", "Bank Transfer", "Other"])
        self.method_combo.setMinimumHeight(38)
        form.addRow(self._label("Payment Method"), self.method_combo)
        
        layout.addLayout(form)
        
        # Pre-fill for editing
        if self.billing_data:
            self.total_input.setValue(float(self.billing_data.get('total_amount', 0)))
            self.paid_input.setValue(float(self.billing_data.get('amount_paid', 0)))
            method = self.billing_data.get('payment_method', 'Cash')
            idx = self.method_combo.findText(method)
            if idx >= 0:
                self.method_combo.setCurrentIndex(idx)
        else:
            self._update_total()
        
        btn_layout = QHBoxLayout()
        btn_layout.addStretch()
        
        cancel_btn = QPushButton("  Cancel")
        cancel_btn.setObjectName("outline_btn")
        cancel_btn.setIcon(qta.icon('fa5s.times', color='#2AACB8'))
        cancel_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        cancel_btn.clicked.connect(self.reject)
        btn_layout.addWidget(cancel_btn)
        
        save_btn = QPushButton("  Save")
        save_btn.setObjectName("success_btn")
        save_btn.setIcon(qta.icon('fa5s.check', color='white'))
        save_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        save_btn.clicked.connect(self.validate_and_accept)
        btn_layout.addWidget(save_btn)
        
        layout.addLayout(btn_layout)
    
    def _label(self, text):
        lbl = QLabel(text)
        lbl.setObjectName("form_label")
        return lbl
    
    def _update_total(self):
        """Calculate total from pre-loaded treatment totals when appointment changes."""
        if hasattr(self, 'appointment_combo') and self.appointment_combo.currentData():
            appointment_id = self.appointment_combo.currentData()
            total = self._treatment_totals.get(appointment_id, 0)
            self.total_input.setValue(float(total))
    
    def validate_and_accept(self):
        """Validate billing inputs before accepting."""
        total = self.total_input.value()
        paid = self.paid_input.value()
        
        if total <= 0:
            QMessageBox.warning(self, "Validation Error",
                "Total amount must be greater than ₱0.00.\n"
                "Make sure the appointment has recorded treatments.")
            return
        if paid < 0:
            QMessageBox.warning(self, "Validation Error", "Amount paid cannot be negative.")
            return
        if not self.billing_data and hasattr(self, 'appointment_combo'):
            if self.appointment_combo.count() == 0:
                QMessageBox.warning(self, "Error", "No appointments found.")
                return
        self.accept()
    
    def get_data(self):
        data = {
            'total_amount': self.total_input.value(),
            'amount_paid': self.paid_input.value(),
            'payment_method': self.method_combo.currentText()
        }
        if hasattr(self, 'appointment_combo'):
            data['appointment_id'] = self.appointment_combo.currentData()
        return data


class ReceiptDialog(QDialog):
    """Beautiful receipt preview with print functionality."""
    
    def __init__(self, parent=None, billing_data=None, treatments=None):
        super().__init__(parent)
        self.billing_data = billing_data or {}
        self.treatments = treatments or []
        self.setWindowTitle("Receipt")
        self.setMinimumSize(520, 650)
        self.setStyleSheet("QDialog { background-color: #F0F6F7; }")
        self.init_ui()
    
    def init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 20, 20, 20)
        layout.setSpacing(12)
        
        # Receipt content browser
        self.receipt_browser = QTextBrowser()
        self.receipt_browser.setOpenExternalLinks(False)
        self.receipt_browser.setStyleSheet(
            "QTextBrowser { background: white; border: 1px solid #D4E6E9; "
            "border-radius: 8px; padding: 10px; font-size: 13px; }"
        )
        self.receipt_browser.setHtml(self._generate_receipt_html())
        layout.addWidget(self.receipt_browser)
        
        # Buttons
        btn_layout = QHBoxLayout()
        btn_layout.addStretch()
        
        close_btn = QPushButton("  Close")
        close_btn.setObjectName("outline_btn")
        close_btn.setIcon(qta.icon('fa5s.times', color='#2AACB8'))
        close_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        close_btn.clicked.connect(self.reject)
        btn_layout.addWidget(close_btn)
        
        print_btn = QPushButton("  Print Receipt")
        print_btn.setObjectName("primary_btn")
        print_btn.setIcon(qta.icon('fa5s.print', color='white'))
        print_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        print_btn.clicked.connect(self._print_receipt)
        btn_layout.addWidget(print_btn)
        
        layout.addLayout(btn_layout)
    
    def _generate_receipt_html(self):
        """Build the receipt as styled HTML."""
        billing = self.billing_data
        if not billing:
            return "<h3 style='color:red;'>Billing record not found.</h3>"
        
        # Get treatments passed from controller
        treatments = self.treatments
        
        # Format values
        total = float(billing['total_amount'])
        paid = float(billing['amount_paid'])
        balance = float(billing['balance'])
        status = billing.get('payment_status', 'Unpaid')
        appt_date = billing.get('appointment_date', '')
        appt_time = billing.get('appointment_time', '')
        date_paid = billing.get('date_paid', '')
        receipt_no = f"HTD-{billing['id']:05d}"
        now = datetime.now().strftime("%b %d, %Y  %I:%M %p")
        
        status_color = '#2E7D32' if status == 'Paid' else '#FB8C00' if status == 'Partial' else '#E53935'
        
        # Build treatment rows
        treatment_rows = ""
        for i, t in enumerate(treatments, 1):
            price = float(t.get('price', 0))
            tooth = t.get('tooth_number', '-') or '-'
            notes = t.get('notes', '') or ''
            notes_html = f'<br><span style="color: #78909C; font-size: 18px;">Note: {notes}</span>' if notes else ''
            treatment_rows += f"""
            <tr>
                <td style="padding: 10px 12px; border-bottom: 1px solid #EEE; font-size: 22px;">{i}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #EEE; font-size: 22px;">{t['service_name']}{notes_html}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #EEE; text-align: center; font-size: 22px;">{tooth}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #EEE; text-align: right; font-size: 22px;">P{price:,.2f}</td>
            </tr>"""
        
        if not treatment_rows:
            treatment_rows = """
            <tr>
                <td colspan="4" style="padding: 18px; text-align: center; color: #999; font-size: 22px;">
                    No treatment details recorded
                </td>
            </tr>"""
        
        html = f"""
        <div style="font-family: 'Segoe UI', Arial, sans-serif; color: #263238; width: 100%; margin: 0 auto; padding: 10px;">
            
            <!-- Header -->
            <div style="text-align: center; padding-bottom: 16px; border-bottom: 4px solid #2AACB8;">
                <h1 style="margin: 0; color: #2AACB8; font-size: 36px;">Happy Tooth Dental Clinic</h1>
                <p style="margin: 4px 0 0 0; color: #78909C; font-size: 22px;">and Services</p>
                <p style="margin: 10px 0 0 0; color: #78909C; font-size: 18px;">Your Smile, Our Priority</p>
            </div>
            
            <!-- Receipt Title -->
            <div style="text-align: center; margin: 20px 0;">
                <h2 style="margin: 0; color: #263238; font-size: 30px; letter-spacing: 3px;">OFFICIAL RECEIPT</h2>
                <p style="margin: 8px 0 0 0; color: #78909C; font-size: 20px;">Receipt No: <b>{receipt_no}</b></p>
                <p style="margin: 4px 0 0 0; color: #78909C; font-size: 18px;">Printed: {now}</p>
            </div>
            
            <!-- Patient & Appointment Info -->
            <table style="width: 100%; margin: 16px 0; font-size: 22px;">
                <tr>
                    <td style="padding: 6px 0; color: #78909C; width: 200px;">Patient:</td>
                    <td style="padding: 6px 0; font-weight: 600;">{billing.get('patient_name', 'N/A')}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 0; color: #78909C;">Dentist:</td>
                    <td style="padding: 6px 0; font-weight: 600;">{billing.get('dentist_name', 'N/A')}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 0; color: #78909C;">Appointment:</td>
                    <td style="padding: 6px 0;">{appt_date} {appt_time if appt_time else ''}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 0; color: #78909C;">Payment Method:</td>
                    <td style="padding: 6px 0;">{billing.get('payment_method', 'N/A')}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 0; color: #78909C;">Generated By:</td>
                    <td style="padding: 6px 0; font-weight: 600;">{billing.get('processed_by_name') or billing.get('generated_by_name', 'N/A') or 'N/A'}</td>
                </tr>
            </table>
            
            <!-- Treatments / Services -->
            <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
                <thead>
                    <tr style="background: #2AACB8; color: white;">
                        <th style="padding: 12px; text-align: left; font-size: 22px;">#</th>
                        <th style="padding: 12px; text-align: left; font-size: 22px;">Service / Treatment</th>
                        <th style="padding: 12px; text-align: center; font-size: 22px;">Tooth</th>
                        <th style="padding: 12px; text-align: right; font-size: 22px;">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {treatment_rows}
                </tbody>
            </table>
            
            <!-- Totals -->
            <div style="border-top: 3px solid #2AACB8; margin-top: 10px; padding-top: 12px;">
                <table style="width: 100%; font-size: 24px;">
                    <tr>
                        <td style="padding: 8px 0; color: #78909C;">Total Amount:</td>
                        <td style="padding: 8px 0; text-align: right; font-weight: 600;">P{total:,.2f}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0; color: #78909C;">Amount Paid:</td>
                        <td style="padding: 8px 0; text-align: right; font-weight: 600; color: #2E7D32;">P{paid:,.2f}</td>
                    </tr>
                    <tr style="border-top: 2px dashed #CCC;">
                        <td style="padding: 10px 0; font-weight: 700; font-size: 28px;">{'Change:' if balance < 0 else 'Balance:'}</td>
                        <td style="padding: 10px 0; text-align: right; font-weight: 700; font-size: 28px; color: {'#2E7D32' if balance <= 0 else '#E53935'};">P{abs(balance):,.2f}</td>
                    </tr>
                </table>
            </div>
            
            <!-- Status Badge -->
            <div style="text-align: center; margin: 20px 0;">
                <span style="background: {status_color}; color: white; padding: 8px 30px; border-radius: 16px; font-size: 22px; font-weight: 600; letter-spacing: 2px;">{status.upper()}</span>
            </div>
            
            {f'<p style="text-align: center; color: #78909C; font-size: 18px;">Date Paid: {date_paid}</p>' if date_paid else ''}
            
            <!-- Footer -->
            <div style="text-align: center; margin-top: 25px; padding-top: 15px; border-top: 2px dashed #D4E6E9;">
                <p style="margin: 0; color: #78909C; font-size: 20px;">Thank you for choosing Happy Tooth Dental Clinic!</p>
                <p style="margin: 6px 0 0 0; color: #B0BEC5; font-size: 16px;">This serves as your official receipt.</p>
            </div>
        </div>
        """
        return html
    
    def _print_receipt(self):
        """Open system print dialog to print the receipt."""
        printer = QPrinter(QPrinter.PrinterMode.ScreenResolution)
        printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
        printer.setPageOrientation(QPageLayout.Orientation.Portrait)
        margins = QMarginsF(15, 15, 15, 15)
        printer.setPageMargins(margins, QPageLayout.Unit.Millimeter)
        
        dialog = QPrintDialog(printer, self)
        dialog.setWindowTitle("Print Receipt")
        if dialog.exec():
            self.receipt_browser.document().print(printer)
            QMessageBox.information(self, "Printed", "Receipt sent to printer successfully!")
